name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Muda para master se a sua branch principal do GitHub se chamar master

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Instalar Dependências
        run: npm ci

      - name: Build do Projeto (Injetando as Variáveis)
        env:
          VITE_CHANNEL_ID: ${{ vars.VITE_CHANNEL_ID }}
          VITE_JWT: ${{ vars.VITE_JWT }}
        run: npm run build

      - name: Deploy para o GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages